GazebosWebApp/Controllers/CurrencyController.cs
using GazebosWebApp.Models;
using GazebosWebApp.Repository;
using System.Net;
using System.Web.Mvc;

namespace GazebosWebApp.Controllers
{
    public class CurrencyController : Controller
    {

        private IGenericRepository<CurrencyModel> repository = null;

        public CurrencyController()
        {
            this.repository = new CurrencyRepository();
        }

        public CurrencyController(IGenericRepository<CurrencyModel> repository)
        {
            this.repository = repository;
        }

        // GET: Currency
        public ActionResult Index()
        {
            //ViewBag.Message = "Currency converter (GBP > PLN).";
            return View();
        }

        // GET: Currency/Index/5
        [HttpPost]
        public ActionResult Index(string amount,
                                  string currencyFrom,
                                  string currencyTo)
        {
            //if (amount.Trim().Length == 0)
            //    ModelState.AddModelError("amount", "Value is required.");

            // var YourRadioButton1 = Request.Form["currencyRadio"];
            CurrencyModel cm = new CurrencyModel();
            cm.RunProcess(amount, currencyFrom, currencyTo);


            //if (!Request.IsAjaxRequest())
                return View(cm);
                          
            //var HttpStatus = ModelState.IsValid ? HttpStatusCode.OK : HttpStatusCode.BadRequest;
            //return new HttpStatusCodeResult(HttpStatus);
        }






    }
}

GazebosWebApp/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "Error404";
    Layout = "~/Views/Shared/_LayoutGazebosMain.cshtml";
}

  <!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">

        <div class="col-lg-12">
            <div class="jumbotron">
                <h1>
                    <span class="error-404">404</span>
                </h1>
                <p>The page you're looking for could not be found. Here are some helpful links to get you back on track:</p>
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>
                        Portfolio
                        <ul>
                            <li>
                                <a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Blog
                        <ul>
                            <li>
                                <a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Other Pages
                        <ul>
                            <li>
                                <a href="full-width-page.html">Full Width Page</a>
                            </li>
                            <li>
                                <a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="404.html">404 Page</a>
                            </li>
                            <li>
                                <a href="pricing-table.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

    </div>

GazebosWebApp/Views/Shared/_ErrorSectionPartial.cshtml
<div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    @Model
 </div>

GazebosWebApp/Views/Shared/_FooterPartial.cshtml
<hr>
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; <a href="http://it.jezile.net" target="_blank">jezile-IT</a> @DateTime.Now.Year</p>
        </div>
    </div>
</footer>

GazebosWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/bootstrap.min.css" rel="stylesheet">

    <!-- My custom CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/custom.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="@Url.Content("~/Content/Gazebos/")font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @*
                <a class="navbar-brand box-shad" href="#">
                    <img src="~/Content/Gazebos/images/anglian-gazebo-logo.png" alt="Anglian Gazebo Limited" />
                </a>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                *@

                <a href="@Url.Action("Index", "Home", new { area = "" })" class="navbar-brand">
                    <i class="glyphicon glyphicon-home"></i>
                    <span class="sr-only"></span>
                </a>
            </div>
            @*
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            *@
        </div>
    </nav>

    @RenderBody()
    <hr>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- jQuery -->
    <script src="@Url.Content("~/Content/Gazebos/")js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/Gazebos/")js/bootstrap.min.js"></script>
    <script src="@Url.Content("~/Content/Gazebos/")js/bootstrap.js"></script>

    <!-- Contact Form JavaScript -->
    <!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <script src="@Url.Content("~/Content/Gazebos/")js/jqBootstrapValidation.js"></script>
    <script src="@Url.Content("~/Content/Gazebos/")js/contact_me.js"></script>

</body>
</html>

GazebosWebApp/Views/Shared/_LayoutGazebosMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/bootstrap.min.css" rel="stylesheet">

    <!-- My custom CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/custom.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="@Url.Content("~/Content/Gazebos/")css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="@Url.Content("~/Content/Gazebos/")font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--Start of Zopim Live Chat Script-->
    @*<script type="text/javascript">
        window.$zopim || (function (d, s) {
            var z = $zopim = function (c) { z._.push(c) }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0]; z.set = function (o) {
                z.set.
                _.push(o)
            }; z._ = []; z.set._ = []; $.async = !0; $.setAttribute("charset", "utf-8");
            $.src = "//v2.zopim.com/?3J6adLsXzrhg05j2rNkutA1dWsuYDGK0"; z.t = +new Date; $.
            type = "text/javascript"; e.parentNode.insertBefore($, e)
        })(document, "script");
    </script>*@
    <!--End of Zopim Live Chat Script-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @*
                <a class="navbar-brand box-shad" href="#">
                    <img src="~/Content/Gazebos/images/anglian-gazebo-logo.png" alt="Anglian Gazebo Limited" />
                </a>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                *@

                <a href="@Url.Action("Index", "Home", new { area = "" })" class="navbar-brand">
                    <i class="glyphicon glyphicon-home"></i>
                    <span class="sr-only"></span>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gazebos <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Sophie</a></li>
                            <li><a href="#">Beatrice</a></li>
                            <li><a href="#">Barbeque</a></li>
                            <li><a href="#">Caroline</a></li>
                            <li><a href="#">Daphne</a></li>
                            <li><a href="#">Elizabeth</a></li>
                            <li><a href="#">Esther</a></li>
                            <li><a href="#">Karen</a></li>
                            <li><a href="#">Jenny</a></li>
                            <li><a href="#">Abigail</a></li>
                            <li><a href="#">Ribs</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Furnitures <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Heart</a></li>
                            <li><a href="#">Flower</a></li>
                            <li><a href="#">Classic 1</a></li>
                            <li><a href="#">Classic 2</a></li>
                            <li><a href="#">William</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Apps <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Currency", new { area = "" })">Currency App</a></li>
                        </ul>
                    </li>
                    <!--li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="full-width.html">Full Width Page</a></li>
                            <li><a href="sidebar.html">Sidebar Page</a></li>
                            <li><a href="faq.html">FAQ</a></li>
                            <li><a href="404.html">404</a></li>
                            <li><a href="pricing.html">Pricing Table</a></li>
                        </ul>
                    </li-->
                    @Html.Partial("_LoginPartial", new { @class = "nav navbar-nav navbar-right" })
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @*<!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Business Name or Tagline</h1>
                </div>
            </div>
        </div>
    </header>*@


    @RenderBody()
    @*<hr>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- jQuery -->
    <script src="@Url.Content("~/Content/Gazebos/")js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/Gazebos/")js/bootstrap.min.js"></script>
    <script src="@Url.Content("~/Content/Gazebos/")js/bootstrap.js"></script>
    
    <!-- Contact Form JavaScript -->
    <!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <script src="@Url.Content("~/Content/Gazebos/")js/jqBootstrapValidation.js"></script>
    
    
    <!-- Script to Activate the Carousel -->
    <script>
        $('.carousel').carousel({
            interval: 5000 //changes the speed
        })

    </script>
</body>
</html>